#in this makemake instead offf all target we keep them isolated to make use of this make file properly to be familier

build:
		gcc displayAllFiles.c -o myexe1
		gcc displayFilesWithTypes.c -o myexe2
		gcc DisplayMaxFileName_Size.c -o myexe3
#		gcc CpData_Src_Dst.c -o myexe4
#		gcc Check_File_Exist_In_Dir.c -o myexe5

clean:
		rm myexe1
		rm myexe2
		rm myexe3
#		rm myexe4
#		rm myexe5

run:
		./myexe1 ${ARGS}
		./myexe2 ${ARGS}
		./myexe3 ${ARGS}
#		./myexe4 ${ARGS}
#		./myexe5 ${ARGS} 


