build:
	gcc OpenFile.c -o myexe
	gcc OpenWithMode.c -o myexe1
	gcc CheckFileOpen_able_To_Open_file.c -o myexe2
	gcc Display_File_Info.c -o myexe3
	gcc ReadFile_N_Bytes.c -o myexe4
	gcc Read_WholeFile.c -o myexe5
	gcc WriteDataToFile.c -o myexe6
	
	

clean:
	rm myexe
	rm myexe1
	rm myexe2
	rm myexe3
	rm myexe4
	rm myexe5
	rm myexe6


run:
	./myexe mydemo.txt
	./myexe1 mydemo.txt
	./myexe2 mydemo.txt O_RDWR
	./myexe3 mydemo.txt 
	./myexe4 mydemo.txt 10
	./myexe5 mydemo.txt
	./myexe6 mydemo.txt
	
